# Generated by Django 3.1.3 on 2020-11-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0002_auto_20201114_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterios_Ganadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=30, verbose_name='Criterio')),
            ],
            options={
                'verbose_name': 'Criterio Ganador',
                'verbose_name_plural': 'Criterios Ganadores',
            },
        ),
        migrations.CreateModel(
            name='Modalidades_Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('equipos_por_grupo', models.SmallIntegerField(verbose_name='Equipos por grupo')),
                ('num_grupos', models.SmallIntegerField(verbose_name='Número de grupos')),
            ],
            options={
                'verbose_name': 'Modalidad de Fase',
                'verbose_name_plural': 'Modalidades de Fase',
            },
        ),
        migrations.CreateModel(
            name='Organizadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30, verbose_name='Usuario')),
                ('contrasena', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='equipos_por_partido',
            field=models.SmallIntegerField(verbose_name='Equipos por partido'),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='part_por_equipo',
            field=models.SmallIntegerField(verbose_name='Participantes por equipo'),
        ),
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('edicion', models.SmallIntegerField(verbose_name='Edición')),
                ('id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTest.juegos')),
                ('id_organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTest.organizadores')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('rol_permiso', models.ManyToManyField(to='appTest.Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('resumen', models.CharField(max_length=100, verbose_name='Resumen')),
                ('cuerpo', models.CharField(max_length=400, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d')),
                ('id_organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTest.organizadores')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='organizadores',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTest.roles'),
        ),
        migrations.CreateModel(
            name='Criterios_Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia', models.SmallIntegerField(verbose_name='Importancia')),
                ('id_crit_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTest.criterios_ganadores')),
                ('id_modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTest.modalidades_fase')),
            ],
        ),
    ]
