# Generated by Django 3.1.3 on 2020-11-15 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0003_auto_20201115_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase_Torneos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='criterios_fase',
            name='id_crit_ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTest.criterios_ganadores'),
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del partido')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('id_fase_torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTest.fase_torneos')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador', models.BooleanField()),
                ('puntos_equipo', models.IntegerField(verbose_name='Puntos del equipo')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTest.equipos')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTest.partidos')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('num_partidos', models.SmallIntegerField(verbose_name='Número de partidos')),
                ('id_mod_fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTest.modalidades_fase')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.AddField(
            model_name='fase_torneos',
            name='id_fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTest.fases'),
        ),
        migrations.AddField(
            model_name='fase_torneos',
            name='id_torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTest.torneos'),
        ),
    ]
