# Generated by Django 3.1.3 on 2020-12-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterios_Ganadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=30, verbose_name='Criterio')),
            ],
            options={
                'verbose_name': 'Criterio Ganador',
                'verbose_name_plural': 'Criterios Ganadores',
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('logo', models.ImageField(upload_to='logos/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Fase_Torneos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('equipos_por_grupo', models.SmallIntegerField(verbose_name='Equipos por grupo')),
                ('num_grupos', models.SmallIntegerField(verbose_name='Número de grupos')),
                ('part_por_equipo', models.SmallIntegerField(verbose_name='Participantes por equipo')),
                ('equipos_por_partido', models.SmallIntegerField(verbose_name='Equipos por partido')),
            ],
            options={
                'verbose_name': 'Modalidad de Fase',
                'verbose_name_plural': 'Modalidades de Fase',
            },
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='Organizadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30, verbose_name='Usuario')),
                ('contrasena', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=100, verbose_name='Email')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='Nickname')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('edicion', models.SmallIntegerField(verbose_name='Edición')),
                ('id_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.juegos')),
                ('id_organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organizadores')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('rol_permiso', models.ManyToManyField(to='main.Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Registro_Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('rol', models.CharField(max_length=2, verbose_name='Rol')),
                ('aprobado', models.BooleanField(default=False)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipos')),
                ('id_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fases')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('cuerpo', models.CharField(max_length=400, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d')),
                ('id_organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organizadores')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del partido')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('id_fase_torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fase_torneos')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador', models.BooleanField()),
                ('puntos_equipo', models.IntegerField(verbose_name='Puntos del equipo')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipos')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partidos')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.AddField(
            model_name='organizadores',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.roles'),
        ),
        migrations.AddField(
            model_name='fase_torneos',
            name='id_fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fases'),
        ),
        migrations.AddField(
            model_name='fase_torneos',
            name='id_torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.torneos'),
        ),
        migrations.CreateModel(
            name='Criterios_Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia', models.SmallIntegerField(verbose_name='Importancia')),
                ('id_crit_ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.criterios_ganadores')),
                ('id_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fases')),
            ],
        ),
    ]
