# Generated by Django 3.1.3 on 2021-01-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tipo_delegado',
            field=models.CharField(choices=[('d', 'delegado'), ('jd', 'delegado y jugador')], default='d', max_length=2, verbose_name='Tipo de delegado'),
        ),
    ]
