# Generated by Django 3.1.4 on 2021-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyparticipation',
            name='rol',
            field=models.CharField(choices=[('j', 'Jugador'), ('d', 'Delegado'), ('jd', 'Delegado y Jugador')], max_length=2, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tipo_delegado',
            field=models.CharField(choices=[('d', 'Delegado'), ('jd', 'Delegado y Jugador')], default='d', max_length=2, verbose_name='Tipo de delegado'),
        ),
    ]
