# Generated by Django 3.1.3 on 2021-01-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='equipos_por_grupo',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='num_grupos',
        ),
    ]
