# Generated by Django 3.1.4 on 2021-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetournament',
            name='equipos_por_grupo',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Equipos por grupo'),
        ),
        migrations.AlterField(
            model_name='stagetournament',
            name='num_grupos',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Numero de grupos'),
        ),
    ]
