# Generated by Django 3.1.4 on 2021-02-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='esport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anotaciones'),
        ),
    ]
