# Generated by Django 3.1.4 on 2021-01-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210118_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetournament',
            name='equipos_por_partido',
            field=models.SmallIntegerField(verbose_name='Equipos por partido'),
        ),
        migrations.AlterField(
            model_name='stagetournament',
            name='participantes_por_equipo',
            field=models.SmallIntegerField(verbose_name='Participantes por equipo'),
        ),
    ]
