# Generated by Django 3.1.3 on 2021-01-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210107_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StageStandard',
        ),
        migrations.DeleteModel(
            name='WinningStandard',
        ),
    ]
