# Generated by Django 3.1.3 on 2020-12-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201216_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permition',
            new_name='Permission',
        ),
    ]
