# Generated by Django 3.1.3 on 2021-01-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tournament_tipo_delegado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='equipos_por_partido',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='part_por_equipo',
        ),
        migrations.AddField(
            model_name='classified',
            name='grupo',
            field=models.CharField(max_length=1, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='stagetournament',
            name='equipos_por_grupo',
            field=models.SmallIntegerField(null=True, verbose_name='Equipos por grupo'),
        ),
        migrations.AddField(
            model_name='stagetournament',
            name='equipos_por_partido',
            field=models.SmallIntegerField(default=2, verbose_name='Equipos por partido'),
        ),
        migrations.AddField(
            model_name='stagetournament',
            name='num_grupos',
            field=models.SmallIntegerField(null=True, verbose_name='Numero de grupos'),
        ),
        migrations.AddField(
            model_name='stagetournament',
            name='participantes_por_equipo',
            field=models.SmallIntegerField(default=1, verbose_name='Participantes por equipo'),
        ),
    ]
