# Generated by Django 3.1.4 on 2021-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210303_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha del partido'),
        ),
    ]
