# Generated by Django 3.1.3 on 2020-12-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201224_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='id_juego',
            new_name='juego',
        ),
        migrations.AlterField(
            model_name='historyparticipation',
            name='rol',
            field=models.CharField(choices=[('j', 'jugador'), ('d', 'delegado'), ('jd', 'delegado y jugador')], max_length=2, verbose_name='Rol'),
        ),
    ]
