# Generated by Django 3.1.4 on 2020-12-31 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_preteamregister_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tournament', verbose_name='Torneo del post'),
        ),
    ]
