# Generated by Django 3.1.4 on 2021-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210217_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Scores'),
        ),
    ]
