# Generated by Django 3.1.4 on 2021-02-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210206_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='preteam_logos'),
        ),
    ]
