# Generated by Django 3.1.3 on 2020-12-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201221_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preteamregister',
            name='comentario',
        ),
        migrations.AddField(
            model_name='preteam',
            name='comentario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentario (opcional)'),
        ),
    ]
