# Generated by Django 3.1.3 on 2021-01-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210118_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetournament',
            name='id_fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stage'),
        ),
    ]
