# Generated by Django 3.1.4 on 2021-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210303_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hora',
            field=models.DateTimeField(default='0000-00-00 00:00:00.000000', verbose_name='Hora del partido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del partido'),
        ),
    ]
