# Generated by Django 3.1.4 on 2021-02-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210208_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos'),
        ),
    ]
