# Generated by Django 3.1.4 on 2021-03-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210303_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='hora',
        ),
    ]
